<?php
/**
 * @file
 * Symfony Dependency Container for Drupal 7.
 */

// Cache key for the dependency injection.
define('SYMFONY_DI_CONTAINER_CACHE_KEY', 'symfony_di_container_cache_key');
define('SYMFONY_CLASS_LOADER_RESGITER_CACHE_KEY', 'symfony_class_loader_register_cache_key');

/**
 * Implements hook_init().
 */
function drupal_symfony_inject_init() {
  if (
    class_exists('Symfony\Component\ClassLoader\ClassLoader') &&
    class_exists('Symfony\Component\DependencyInjection\ContainerBuilder')
  ) {
    global $_drupal_symfony_di_container;

    // Initialize global Symfony di container.
    try {
      // Add the file which defines the helpers.
      module_load_include('inc', 'drupal_symfony_inject', 'helpers/drupal_symfony_inject.helpers');

      // Register namespaces.
      drupal_symfony_inject_register_class_loader();

      // Initialize the container and assign it to the global variable.
      $_drupal_symfony_di_container = drupal_symfony_inject_get_container_builder();

      $config = new \ProxyManager\Configuration();
      $config->setProxiesTargetDir('/tmp/doctrine/proxies');

      // then register the autoloader
      spl_autoload_register($config->getProxyAutoloader());
    }
    catch(Exception $exp) {
      watchdog_exception('drupal_symfony_inject', $exp);
    }
  }
  else {
    watchdog('drupal_symfony_inject', 'Symfony ClassLoader not found.', array(), WATCHDOG_ERROR);
  }
}
