<?php

/**
 * Install/upgrade hooks.
 */

/**
 * Implements hook_install().
 */
function drupal_symfony_inject_install() {
  // Set a low module weight to ensure this module is enabled before those that
  // depend on it.
  db_query("UPDATE {system} SET weight = -99 WHERE name = 'drupal_symfony_inject'");
}

/**
 * Set a low module weight to ensure this module is enabled before those that
 * depend on it.
 */
function drupal_symfony_inject_update_7101() {
  db_query("UPDATE {system} SET weight = -99 WHERE name = 'drupal_symfony_inject' AND type = 'module'");
}
