<?php

/**
 * Install/upgrade hooks.
 */

/**
 * Implements hook_install().
 */
function drupal_symfony_inject_install() {
  // Set a low module weight to ensure this module is enabled before those that
  // depend on it.
  db_query("UPDATE {system} SET weight = -99 WHERE name = 'drupal_symfony_inject'");
  db_query("UPDATE {system} SET weight = -100 WHERE name = 'composer_manager' AND type = 'module'");
}

/**
 * Implements hook_requirements().
 */
function drupal_symfony_inject_requirements($phase) {
  // load the main module file because we need access
  // to SYMFONY_CLASS_LOADER_PROXIES_DIR constant
  module_load_include('module', 'drupal_symfony_inject');

  $requirements = array();
  // Ensure translations don't break during installation.
  $t = get_t();

  // Require presence of our proxy cache directory.
  $proxies_path = variable_get(SYMFONY_CLASS_LOADER_PROXIES_DIR, '/tmp/doctrine/proxies');
  $requirements['drupal_symfony_inject'] = array(
    'title' => $t('Drupal symfony inject'),
    'value' => $t('Generating proxies to @proxies_path.', array('@proxies_path' => $proxies_path)),
  );
  if (!is_dir($proxies_path) || !is_writable($proxies_path)) {
    $requirements['drupal_symfony_inject'] += array(
      'severity' => REQUIREMENT_ERROR,
      'description' => $t('This directory must exist, and the webserver must have permission to write to it.'),
    );
  }

  return $requirements;
}

/**
 * Set a low module weight to ensure this module is enabled before those that
 * depend on it.
 */
function drupal_symfony_inject_update_7101() {
  db_query("UPDATE {system} SET weight = -99 WHERE name = 'drupal_symfony_inject' AND type = 'module'");
  db_query("UPDATE {system} SET weight = -100 WHERE name = 'composer_manager' AND type = 'module'");
}
